<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="KeepMyOverridesPls.csproj.user" Condition="Exists('KeepMyOverridesPls.csproj.user')"/>
  
  <PropertyGroup>
    <ImportBSMTTargets>true</ImportBSMTTargets>
    <BSMTProjectType>BSIPA</BSMTProjectType>
    <GameDirectory>D:\BSManager\BSInstances\1.45.1</GameDirectory>
    <CopyPDB>false</CopyPDB>
    <DisableCopyToGame>false</DisableCopyToGame>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableFrameworkPathOverride>true</EnableFrameworkPathOverride>
    <FrameworkPathOverride>$(GameDirectory)\Beat Saber_Data\Managed</FrameworkPathOverride>
    <MarkPackageReferencesAsExternallyResolved>false</MarkPackageReferencesAsExternallyResolved>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BeatSaberModdingTools.Tasks" Version="2.0.0-beta7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="BeatSaber.ViewSystem">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\BeatSaber.ViewSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="DataModels" Publicize="true">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\DataModels.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="HMUI">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\HMUI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="IPA.Loader">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\IPA.Loader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Main" Publicize="true">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\Main.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="mscorlib"/>
    <Reference Include="netstandard"/>
    <Reference Include="SiraUtil">
      <HintPath>$(GameDirectory)\Plugins\SiraUtil.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System"/>
    <Reference Include="System.Core"/>
    <Reference Include="UnityEngine">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Zenject">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\Zenject.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Zenject-usage">
      <HintPath>$(GameDirectory)\Beat Saber_Data\Managed\Zenject-usage.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="KeepMyOverridesPls.csproj.user" />
  </ItemGroup>
  
</Project>
